# This pipeline automates testing, building, pushing, deploying, and swapping an Azure App Service container.

trigger:
  branches:
    include:
      - main  # Runs the pipeline when changes are pushed to the main branch

# Define variables for easier management
variables:
  ACR_NAME: "typescriptimage"  # Azure Container Registry name
  IMAGE_NAME: "my-app"  # Docker image name
  TAG: "$(Build.BuildId)"  # Unique tag for the image (Build ID)
  RESOURCE_GROUP: "linux-agent_group"  # Azure resource group
  MANAGED_IDENTITY_NAME: "a717f3e4-b10b-4a70-b565-a471734765b7"  # Managed identity for Azure authentication
  APP_NAME: "typescript"  # Azure Web App name
  SLOT_NAME: "staging"  # Deployment slot
  APP_PORT: "5000"  # Application port

# Stage 1: Run Unit and Integration Tests
stages:
- stage: Test
  displayName: "Run Unit and Integration Tests"
  jobs:
  - job: RunTests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: "Install Node.js"

    - script: |
        npm ci  # Install dependencies
        npm run test  # Run tests
      displayName: "Run Test Suite"
      workingDirectory: $(System.DefaultWorkingDirectory)

# Stage 2: Build & Push Docker Image to Azure Container Registry
- stage: BuildAndPush
  displayName: "Build & Push Docker Image"
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: BuildAndPushImage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Cache@2
      inputs:
        key: 'docker | "$(Agent.OS)" | Dockerfile'  # Cache key based on OS and Dockerfile
        restoreKeys: |
          docker | "$(Agent.OS)"
        path: '/tmp/docker-cache'
      displayName: "Cache Docker Layers"

    - script: |
        az login --identity --client-id $(MANAGED_IDENTITY_NAME)  # Authenticate using Managed Identity
        az acr login --name $(ACR_NAME)  # Login to Azure Container Registry
        docker build --cache-from $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest \
          -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG) .  # Build Docker image
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG)  # Push image to ACR
      displayName: "Build and Push Docker Image"

# Stage 3: Deploy to Staging Slot
- stage: DeployToStaging
  displayName: "Deploy to Staging Slot"
  dependsOn: BuildAndPush
  condition: succeeded()
  jobs:
  - job: DeployContainerToStaging
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        az login --identity --client-id $(MANAGED_IDENTITY_NAME) --allow-no-subscriptions
        az webapp deployment slot create --name $(APP_NAME) --resource-group $(RESOURCE_GROUP) --slot $(SLOT_NAME) || echo "Slot already exists"
        az webapp config container set --name $(APP_NAME) --resource-group $(RESOURCE_GROUP) --slot $(SLOT_NAME) \
          --container-image-name $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG) \
          --container-registry-url https://$(ACR_NAME).azurecr.io
        az webapp config appsettings set --name $(APP_NAME) --resource-group $(RESOURCE_GROUP) --slot $(SLOT_NAME) \
          --settings WEBSITES_PORT=$(APP_PORT)
        az webapp restart --name $(APP_NAME) --resource-group $(RESOURCE_GROUP) --slot $(SLOT_NAME)
      displayName: "Deploy and Configure Staging Slot"

# Stage 4: Health Check for Staging Slot
- stage: HealthCheckStaging
  displayName: "Verify Staging Slot Health"
  dependsOn: DeployToStaging
  condition: succeeded()
  jobs:
  - job: CheckStagingHealth
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        sleep 10  # Wait for service to start
        curl -f https://$(APP_NAME)-$(SLOT_NAME).azurewebsites.net/health || exit 1
      displayName: "Check Staging Slot Health"

# Stage 5: Swap Staging Slot to Production
- stage: SwapToProduction
  displayName: "Swap Staging to Production"
  dependsOn: HealthCheckStaging
  condition: succeeded()
  jobs:
  - job: SwapSlots
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        az login --identity --client-id $(MANAGED_IDENTITY_NAME) --allow-no-subscriptions
        az webapp deployment slot swap --name $(APP_NAME) --resource-group $(RESOURCE_GROUP) --slot $(SLOT_NAME)
      displayName: "Swap Staging Slot to Production"

# Stage 6: Final Health Check for Production
- stage: FinalHealthCheck
  displayName: "Verify Production Health"
  dependsOn: SwapToProduction
  condition: succeeded()
  jobs:
  - job: CheckProductionHealth
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        sleep 10  # Wait for deployment to settle
        curl -f https://$(APP_NAME).azurewebsites.net/health || exit 1
      displayName: "Check Production Health"
